Fix tabs in files, conforming to .github/CONTRIBUTING.md file.
CONTRIBUTING.md at root directory do not mention tabs/spaces.

diff --git a/target/postgrey/postgrey.init b/target/postgrey/postgrey.init
--- a/target/postgrey/postgrey.init
+++ b/target/postgrey/postgrey.init
@@ -1,4 +1,5 @@
 #!/bin/sh
+# vim: et ai si ts=2 sts=2 sw=2
 #
 # postgrey      start/stop the postgrey greylisting deamon for postfix
 #               (priority should be smaller than that of postfix)
@@ -37,105 +38,104 @@ test -x $DAEMON || exit 0
 # Read config file if it is present.
 if [ -r /etc/default/$DAEMON_NAME ]
 then
-    . /etc/default/$DAEMON_NAME
+  . /etc/default/$DAEMON_NAME
 fi
 
 POSTGREY_OPTS="--pidfile=$PIDFILE --daemonize $POSTGREY_OPTS"
 if [ -z "$POSTGREY_TEXT" ]; then
-    POSTGREY_TEXT_OPT=""
+  POSTGREY_TEXT_OPT=""
 else
-    POSTGREY_TEXT_OPT="--greylist-text=$POSTGREY_TEXT"
+  POSTGREY_TEXT_OPT="--greylist-text=$POSTGREY_TEXT"
 fi
 
 ret=0
 
 do_start()
 {
-        # Return
-        #   0 if daemon has been started
-        #   1 if daemon was already running
-        #   2 if daemon could not be started
-        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-                || return 1
-        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-                $POSTGREY_OPTS "$POSTGREY_TEXT_OPT" \
-                || return 2
+  # Return
+  #   0 if daemon has been started
+  #   1 if daemon was already running
+  #   2 if daemon could not be started
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+    || return 1
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+    $POSTGREY_OPTS "$POSTGREY_TEXT_OPT" \
+    || return 2
 }
 
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-        start-stop-daemon --user $DAEMON_USER --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
-        RETVAL="$?"
-        [ "$RETVAL" = 2 ] && return 2
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  start-stop-daemon --user $DAEMON_USER --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+  RETVAL="$?"
+  [ "$RETVAL" = 2 ] && return 2
 
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --user $DAEMON_USER --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
+  # Wait for children to finish too if this is a daemon that forks
+  # and if the daemon is only ever run from this initscript.
+  # If the above conditions are not satisfied then add some other code
+  # that waits for the process to drop all resources that could be
+  # needed by services started subsequently.  A last resort is to
+  # sleep for some time.
+  start-stop-daemon --user $DAEMON_USER --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+  [ "$?" = 2 ] && return 2
+  # Many daemons don't delete their pidfiles when they exit.
+  rm -f $PIDFILE
+  return "$RETVAL"
 
 }
 
 do_reload()
 {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE
-	return 0
+  #
+  # If the daemon can reload its configuration without
+  # restarting (for example, when it is sent a SIGHUP),
+  # then implement that here.
+  #
+  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE
+  return 0
 }
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$DAEMON_NAME"
-        do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-        ;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$DAEMON_NAME"
+    do_start
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$DAEMON_NAME"
-        do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-        ;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$DAEMON_NAME"
+    do_stop
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   reload|force-reload)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC" "$DAEMON_NAME"
-        do_reload
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-        ;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC" "$DAEMON_NAME"
+    do_reload
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   restart)
-        do_stop
-        do_start
-        ;;
+    do_stop
+    do_start
+    ;;
   status)
-        status_of_proc -p $PIDFILE $DAEMON "$DAEMON_NAME" 2>/dev/null
-        ret=$?
-        ;;
-
+    status_of_proc -p $PIDFILE $DAEMON "$DAEMON_NAME" 2>/dev/null
+    ret=$?
+    ;;
   *)
-        echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload|status}" >&2
-        exit 1
-        ;;
+    echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload|status}" >&2
+    exit 1
+    ;;
 esac
 
 exit $ret
