refactor: `addmailuser` + `adddovecotmasteruser`
These two are very similar, updated together.

Restructures logic into functions, additional comments, local vars.

diff --git a/target/bin/addmailuser b/target/bin/addmailuser
--- a/target/bin/addmailuser
+++ b/target/bin/addmailuser
@@ -5,8 +5,6 @@
 # shellcheck source=../scripts/helpers/index.sh
 source /usr/local/bin/helpers/index.sh
 
-DATABASE='/tmp/docker-mailserver/postfix-accounts.cf'
-
 function __usage
 {
   printf '%s' "${PURPLE}ADDMAILUSER${RED}(${YELLOW}8${RED})
@@ -33,42 +31,75 @@ ${ORANGE}EXIT STATUS${RESET}
 "
 }
 
+function _validate_parameters
+{
+  [[ -z ${FULL_EMAIL} ]] && { __usage ; _exit_with_error 'No username specified' ; }
+  [[ ${FULL_EMAIL} =~ .*\@.* ]] || { __usage ; _exit_with_error 'Username must include the domain' ; }
+}
+
+function _add_account
+{
+  local DATABASE='/tmp/docker-mailserver/postfix-accounts.cf'
+  touch "${DATABASE}"
+  _create_lock # Protect config file with lock to avoid race conditions
+
+  # Escaped values for use in regex patterns:
+  local _EMAIL_=$(_escape "${FULL_EMAIL}")
+
+  function _account_already_exists
+  {
+    # `|` is a delimter between the account identity (_EMAIL_) and the hashed password
+    grep -qi "^${_EMAIL_}|" "${DATABASE}" 2>/dev/null
+  }
+
+  function _hash_password
+  {
+    # If no password was provided, request one interactively:
+    if [[ -z ${PASSWD} ]]
+    then
+      read -r -s -p 'Enter Password: ' PASSWD
+      echo
+      [[ -z ${PASSWD} ]] && _exit_with_error 'Password must not be empty'
+    fi
+
+    # Create the hashed password, then add an account entry into the DATABASE:
+    local HASH=$(doveadm pw -s SHA512-CRYPT -u "${FULL_EMAIL}" -p "${PASSWD}")
+    echo "${FULL_EMAIL}|${HASH}" >> "${DATABASE}"
+  }
+
+  if _account_already_exists
+  then
+    _exit_with_error "User '${FULL_EMAIL}' already exists"
+  fi
+
+  _hash_password
+}
+
+# Tests fail if the creation of /var/mail/${DOMAIN}/${USER} doesn't happen fast enough after addmailuser executes (check-for-changes.sh race-condition)
+# Prevent infinite loop in tests like "checking accounts: user3 should have been added to /tmp/docker-mailserver/postfix-accounts.cf even when that file does not exist"
+function _wait_until_account_maildir_exists
+{
+  if [[ -e ${CHKSUM_FILE} ]]
+  then
+    local USER="${FULL_EMAIL%@*}"
+    local DOMAIN="${FULL_EMAIL#*@}"
+
+    while [[ ! -d "/var/mail/${DOMAIN}/${USER}" ]]
+    do
+      _log 'info' "Waiting for dovecot to create '/var/mail/${DOMAIN}/${USER}/'"
+      sleep 1
+    done
+  fi
+}
+
 [[ ${1:-} == 'help' ]] && { __usage ; exit 0 ; }
 
 FULL_EMAIL="${1}"
 shift
 PASSWD="${*}"
 
-[[ -z ${FULL_EMAIL} ]] && { __usage ; _exit_with_error 'No username specified' ; }
-[[ ${FULL_EMAIL} =~ .*\@.* ]] || { __usage ; _exit_with_error 'Username must include the domain' ; }
-
-touch "${DATABASE}"
-_create_lock # Protect config file with lock to avoid race conditions
-if grep -qi "^$(_escape "${FULL_EMAIL}")|" "${DATABASE}"
-then
-  _exit_with_error "User '${FULL_EMAIL}' already exists"
-fi
-
-if [[ -z ${PASSWD} ]]
-then
-  read -r -s -p "Enter Password: " PASSWD
-  echo
-  [[ -z ${PASSWD} ]] && _exit_with_error "Password must not be empty"
-fi
-
-HASH=$(doveadm pw -s SHA512-CRYPT -u "${FULL_EMAIL}" -p "${PASSWD}")
-echo "${FULL_EMAIL}|${HASH}" >> "${DATABASE}"
-
-USER="${FULL_EMAIL%@*}"
-DOMAIN="${FULL_EMAIL#*@}"
-
-# Tests fail if the creation of /var/mail/${DOMAIN}/${USER} doesn't happen fast enough after addmailuser executes (check-for-changes.sh race-condition)
-# Prevent infinite loop in tests like "checking accounts: user3 should have been added to /tmp/docker-mailserver/postfix-accounts.cf even when that file does not exist"
-if [[ -e ${CHKSUM_FILE} ]]
-then
-  while [[ ! -d "/var/mail/${DOMAIN}/${USER}" ]]
-  do
-    _log 'info' "Waiting for dovecot to create '/var/mail/${DOMAIN}/${USER}/'"
-    sleep 1
-  done
-fi
+_validate_parameters
+_add_account
+# Change Detection will be triggered from DATABASE update via _add_account,
+# block until processed (actual account creation handled there):
+_wait_until_account_maildir_exists
