refactored scripts located under `target/bin/`
The scripts under `target/bin/` now use the new log and I replaced some
`""` with `''` on the way. The functionality stays the same, this mostly
style and log.

diff --git a/target/bin/delmailuser b/target/bin/delmailuser
--- a/target/bin/delmailuser
+++ b/target/bin/delmailuser
@@ -67,7 +67,7 @@ do
 
     * )
       __usage
-      _errex "The option ${OPT} is unknown."
+      _errex "The option '${OPT}' is unknown"
       ;;
 
   esac
@@ -103,7 +103,7 @@ do
   then
     if ! sedfile --strict -i "/^${EMAIL}|/d" "${DATABASE}"
     then
-      echo "${UNESCAPED_EMAIL} couldn't be deleted in ${DATABASE}." >&2
+      _log 'error' "'${UNESCAPED_EMAIL}' couldn't be deleted in '${DATABASE}'" >&2
       ERROR=true
     fi
   fi
@@ -116,9 +116,9 @@ do
       -e "/ ${EMAIL}$/d" -e "s/,${EMAIL}//g" -e "s/${EMAIL},//g" \
       "${ALIAS_DATABASE}"
     then
-      echo "${UNESCAPED_EMAIL} and potential aliases deleted."
+      _log 'info' "'${UNESCAPED_EMAIL}' and potential aliases deleted"
     else
-      echo "Aliases for ${UNESCAPED_EMAIL} couldn't be deleted in ${ALIAS_DATABASE}." >&2
+      _log 'error' "Aliases for '${UNESCAPED_EMAIL}' couldn't be deleted in '${ALIAS_DATABASE}'" >&2
       ERROR=true
     fi
   fi
@@ -128,7 +128,7 @@ do
   then
     if ! sedfile --strict -i -e "/^${EMAIL}:.*$/d" "${QUOTA_DATABASE}"
     then
-      echo "Quota for ${UNESCAPED_EMAIL} couldn't be deleted in ${QUOTA_DATABASE}." >&2
+      _log 'warn' "Quota for '${UNESCAPED_EMAIL}' couldn't be deleted in '${QUOTA_DATABASE}'" >&2
     fi
   fi
 
@@ -144,17 +144,18 @@ use 'sudo docker exec mailserver rm -R /var/mail/${DOMAIN}/${USER}'"
   then
     if rm -R "/var/mail/${DOMAIN}/${USER}"
     then
-      echo "Mailbox deleted."
+      _log 'info' 'Mailbox deleted'
     else
-      echo "Mailbox couldn't be deleted." >&2
+      _log 'error' 'Mailbox could not be deleted' >&2
       ERROR=true
     fi
-    rmdir "/var/mail/${DOMAIN}" 2>/dev/null || true
+    rm -rf "/var/mail/${DOMAIN}"
   else
-    echo "Mailbox directory '/var/mail/${DOMAIN}/${USER}' did not exist." >&2
+    log 'error' "Mailbox directory '/var/mail/${DOMAIN}/${USER}' did not exist" >&2
     ERROR=true
   fi
 
-  ${ERROR} && _errex 'See the messages above.'
+  ${ERROR} && _errex 'See the error message(s) above'
 done
+
 exit 0
diff --git a/target/bin/fail2ban b/target/bin/fail2ban
--- a/target/bin/fail2ban
+++ b/target/bin/fail2ban
@@ -16,7 +16,7 @@ Possible causes for this error are
 3. Host is configured incorrectly
 
 Aborting...
-"
+" >&2
 
   exit 1
 fi
@@ -41,21 +41,21 @@ then
 
     if [[ -n ${BANNED_IP} ]]
     then
-      echo "Banned in ${JAIL}: ${BANNED_IP//$'\n'/, }"
+      echo -e "Banned in ${JAIL}: ${BANNED_IP//$'\n'/, }"
       IP_COUNT=$(( IP_COUNT + 1 ))
     fi
   done
 
   if [[ ${IP_COUNT} -eq 0 ]]
   then
-    echo "No IPs have been banned."
+    _log 'info' 'No IPs have been banned'
   fi
 
 else
 
-  case ${1} in
+  case "${1}" in
 
-    unban)
+    ( 'unban' )
       shift
       if [[ -n ${1} ]]
       then
@@ -68,14 +68,14 @@ else
         done
 
       else
-        echo "You need to specify an IP address. Run './setup.sh debug fail2ban' to get a list of banned IP addresses." >&2
+        log 'warn' "You need to specify an IP address. Run './setup.sh debug fail2ban' to get a list of banned IP addresses."
         exit 0
       fi
       ;;
 
-    *)
+    ( * )
       usage
-      _errex "unknown command: ${1}"
+      _errex "Unknown command: ${1}"
       ;;
 
   esac
diff --git a/target/bin/sedfile b/target/bin/sedfile
--- a/target/bin/sedfile
+++ b/target/bin/sedfile
@@ -14,11 +14,12 @@ set -ueo pipefail
 HASHTOOL="sha1sum"
 SKIP_ERROR=0
 
+function usage { echo "Usage: ${0} -i <replace/delete operation> <file>" ; }
+
 if [[ $# -lt 3 ]]
 then
-  echo "Error:  At least, three parameters must be given."
-  echo "Syntax: sedfile -i <replace/delete operation> <file>"
-  echo
+  usage
+  _log 'error' 'At least three parameters must be given'
   exit 1
 fi >&2
 
@@ -39,8 +40,8 @@ NEW=$(${HASHTOOL} "${FILE}")
 # fail if file was not modified
 if [[ ${OLD} == "${NEW}" ]] && [[ ${SKIP_ERROR} -eq 0 ]]
 then
-  echo "Error: sed $*"
+  echo "Error: sed $*" >&2
   exit 1
-fi >&2
+fi
 
 exit 0
