complete refactor for target/bin/

diff --git a/target/bin/delmailuser b/target/bin/delmailuser
--- a/target/bin/delmailuser
+++ b/target/bin/delmailuser
@@ -1,69 +1,90 @@
 #! /bin/bash
+# shellcheck disable=SC2094
+
 
 DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}
 ALIAS_DATABASE="/tmp/docker-mailserver/postfix-virtual.cf"
 QUOTA_DATABASE="/tmp/docker-mailserver/dovecot-quotas.cf"
 
-usage() {
-	echo "Usage: delmailuser <-y> <user@domain> <user2@anotherdomain> ..."
-	echo "	-y: don't prompt for confirmations"
+function usage
+{
+  echo "Usage: delmailuser <-y> <user@domain> <user2@anotherdomain> ..."
+  echo "	-y: don't prompt for confirmations"
 }
 
-errex() {
-	echo -e "$@" 1>&2
-	exit 1
-}
+function errex  { echo "${@}" 1>&2 ; exit 1 ; }
+function escape { echo "${1//./\\.}" ; }
 
-escape() {
-	echo "${1//./\\.}"
-}
-
-while getopts ":y" OPT; do
-  case $OPT in
+while getopts ":y" OPT
+do
+  case ${OPT} in
     y)
       MAILDEL="y"
       ;;
-   \?)
-		 usage; errex "Invalid option: -$OPTARG"
-     ;;
+    \?)
+      usage
+      errex "Invalid option: -${OPTARG}"
+      ;;
+    *)
+      usage
+      errex "Invalid option: -${OPTARG}"
+      ;;
   esac
 done
 
 shift $((OPTIND-1))
 
-[ -z "$@" ] && { usage; errex "No user specifed"; }
-[ -s "$DATABASE" ] || exit 0
+[[ -z ${*} ]] && { usage ; errex "No user specifed" ; }
+[[ -s ${DATABASE} ]] || exit 0
 
 # Protect config file with lock to avoid race conditions
 (
   flock -e 200
 
-  for USER in "$@"; do
+  for USER in "${@}"
+  do
     # very simple plausibility check
-    [[ "$USER" != *"@"*"."* ]] && errex "No valid address: $USER"
-    MAILARR=(${USER//@/ })
-    # XXX $USER must not contain /s and other syntactic characters
-    USER=$(escape "$USER")
-    sed -i "/^"$USER"|/d" $DATABASE
-    [ $? != 0 ] && errex "$USER couldn't be deleted in $DATABASE. $?"
-    # Delete all aliases where the user is the only recipient( " $USER$" )
-    # Delete user only for all aliases that deliver to multiple recipients ( ",$USER" "$USER," )
-    sed -i -e "/ "$USER"$/d" \
-        -e "s/,"$USER"//g" \
-        -e "s/"$USER",//g" $ALIAS_DATABASE
-    [ $? = 0 ] && echo "$USER and potential aliases deleted." || errex "Aliases for $USER couldn't be deleted in $ALIAS_DATABASE. $?"
-    # remove quota directives
-    if [ -f "$QUOTA_DATABASE" ]; then
-      sed -i -e "/^$USER:.*$/d" $QUOTA_DATABASE || errex "Quota for $USER couldn't be deleted in $QUOTA_DATABASE. $?"
+    [[ ${USER} != *"@"*"."* ]] && errex "No valid address: ${USER}"
+
+    declare -a MAILARR
+    MAILARR[0]="${USER%@*}"
+    MAILARR[1]="${USER#*@}"
+
+    # XXX ${USER} must not contain /s and other syntactic characters
+    USER=$(escape "${USER}")
+
+    if ! sed -i "/^""${USER}""|/d" "${DATABASE}"
+    then
+      errex "${USER} couldn't be deleted in ${DATABASE}. ${?}"
     fi
 
-    if [ "$MAILDEL" != "y" ]; then
-      read -p "Do you want to delete the mailbox as well(all mails will be removed)?(y/n) " MAILDEL
+    # Delete all aliases where the user is the only recipient( " ${USER$}" )
+    # Delete user only for all aliases that deliver to multiple recipients ( ",${USER}" "${USER,}" )
+    if sed -i -e "/ ""${USER}""$/d" \
+        -e "s/,""${USER}""//g" \
+        -e "s/""${USER}"",//g" "${ALIAS_DATABASE}"
+    then
+      echo "${USER} and potential aliases deleted." || errex "Aliases for ${USER} couldn't be deleted in ${ALIAS_DATABASE}. ${?}"
+    fi
+
+    # remove quota directives
+    if [[ -f ${QUOTA_DATABASE} ]]
+    then
+      sed -i -e "/^${USER}:.*$/d" "${QUOTA_DATABASE}" || errex "Quota for ${USER} couldn't be deleted in ${QUOTA_DATABASE}. ${?}"
+    fi
+
+    if [[ ${MAILDEL} != "y" ]]
+    then
+      read -r -p "Do you want to delete the mailbox as well(all mails will be removed)?(y/n) " MAILDEL
       echo
     fi
-    [ "$MAILDEL" != "y" ] && errex "Leaving the mailbox untouched. If you want to delete it at a later point use \"sudo docker exec mail rm -R /var/mail/${MAILARR[1]}/${MAILARR[0]}\""
-    rm -r -f /var/mail/${MAILARR[1]}/${MAILARR[0]}
-    [ $? = 0 ] && echo "Mailbox deleted." || errex "Mailbox couldn't be deleted: $?"
+
+    [[ ${MAILDEL} != "y" ]] && errex "Leaving the mailbox untouched. If you want to delete it at a later point use \"sudo docker exec mail rm -R /var/mail/${MAILARR[1]}/${MAILARR[0]}\""
+
+    if rm -r -f "/var/mail/${MAILARR[1]}/${MAILARR[0]}"
+    then
+      echo "Mailbox deleted." || errex "Mailbox couldn't be deleted: ${?}"
+    fi
   done
 
-) 200<$DATABASE
+) 200< "${DATABASE}"
