updated addalias,delalias,delmailuser,updatemailuser and added modified tests

diff --git a/target/bin/delmailuser b/target/bin/delmailuser
--- a/target/bin/delmailuser
+++ b/target/bin/delmailuser
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}
-ALIAS_DATABASE=${ALIAS_DATABASE:-/tmp/docker-mailserver/postfix-virtual.cf}
+ALIAS_DATABASE="/tmp/docker-mailserver/postfix-virtual.cf"
 
 usage() {
 	echo "Usage: delmailuser <-y> <user@domain> <user2@anotherdomain> ..."
@@ -31,22 +31,27 @@ done
 shift $((OPTIND-1))
 
 [ -z "$@" ] && { usage; errex "No user specifed"; }
-[ -s "$DATABASE" ] || errex "Database not found: $DATABASE"
+[ -s "$DATABASE" ] || exit 0
 
 for USER in "$@"; do
+	#very simple plausibility check
 	[[ "$USER" != *"@"*"."* ]] && errex "No valid address: $USER"
-	#USER="$1"
-	# XXX $USER must not contain /s and other syntactic characters
 	MAILARR=(${USER//@/ })
+	# XXX $USER must not contain /s and other syntactic characters
 	USER=$(escape "$USER")
 	sed -i "/^"$USER"|/d" $DATABASE
-	sed -i "/"$USER"|/d" $ALIAS_DATABASE
-	echo "$USER and potential aliases deleted."
+	[ $? != 0 ] && errex "$USER couldn't be deleted in $DATABASE. $?"
+	# Delete all aliases where the user is the only recipient( " $USER$" )
+	# Delete user only for all aliases that deliver to multiple recipients ( ",$USER" "$USER," )
+	sed -i -e "/ "$USER"$/d" \
+				 -e "s/,"$USER"//g" \
+				 -e "s/"$USER",//g" $ALIAS_DATABASE
+	[ $? = 0 ] && echo "$USER and potential aliases deleted." || errex "Aliases for $USER couldn't be deleted in $ALIAS_DATABASE. $?"
 	if [ "$MAILDEL" != "y" ]; then
 	  read -p "Do you want to delete the maildir as well(all mails will be removed)?(y/n) " MAILDEL
 		echo
 	fi
 	[ "$MAILDEL" != "y" ] && errex "Leaving the maildir untouched. If you want to delete it at a later point use \"sudo docker exec mail rm -R /var/mail/${MAILARR[1]}/${MAILARR[0]}\""
 	rm -r -f /var/mail/${MAILARR[1]}/${MAILARR[0]}
-	echo "Maildir deleted."
+	[ $? = 0 ] && echo "Maildir deleted." || errex "Maildir couldn't be deleted: $?"
 done
