incorporating maintainers' proposals

diff --git a/target/bin/delmailuser b/target/bin/delmailuser
--- a/target/bin/delmailuser
+++ b/target/bin/delmailuser
@@ -21,7 +21,7 @@ function __usage
     delmailuser - delete a user and related data
 
 \e[38;5;214mSYNOPSIS\e[39m
-    ./setup.sh email del [ OPTIONS ] { <MAIL ADDRESS> [<MAIL ADDRESS 2>\e[31m...\e[39m] \e[31m|\e[39m help }
+    ./setup.sh email del [ OPTIONS ] { <MAIL ADDRESS> \e[31m|\e[39m help }
 
 \e[38;5;214mDESCRIPTION\e[39m
     Delete a mail user, aliases, quotas and mail data.
@@ -34,13 +34,13 @@ function __usage
         Show this help dialogue.
 
 \e[38;5;214mEXAMPLES\e[39m
-    ./setup.sh email del -y test@domain.com another-test@domain.com
-        Delete all mail data for the users 'test' and 'another-test'
-        and do not prompt to ask if all mail data should be deleted.
+    \e[37m./setup.sh email del woohoo@some-domain.org\e[39m
+        Delete the mail user, quotas and aliases, but ask
+        again whether mailbox data should be deleted.
 
-    ./setup.sh email del woohoo@some-domain.org
-        Delete the mail user, quotas and aliases, but ask again whether
-        mailbox data should be deleted.
+    \e[37m./setup.sh email del -y test@domain.com\e[39m
+        Delete all mail data for the users 'test' and do not
+        prompt to ask if all mail data should be deleted.
 
 \e[38;5;214mEXIT STATUS\e[39m
     Exit status is 0 if command was successful, and 1 if there was an error.
@@ -67,8 +67,7 @@ do
 
     * )
       __usage
-      echo "The option ${OPT} is unknown." >&2
-      exit 1
+      errex "The option ${OPT} is unknown."
       ;;
 
   esac
@@ -89,41 +88,41 @@ fi
 
 (
   flock -e 200
+  unset EMAIL USER DOMAIN
+
   ERROR=false
-  USER="${*}"
+  EMAIL="${*}"
 
   # very simple plausibility check
-  [[ ${USER} != *@*.* ]] && errex "No valid address: ${USER}"
+  [[ ${EMAIL} != *@*.* ]] && errex "No valid address: ${EMAIL}"
 
-  unset MAILARR
-  declare -a MAILARR
-  MAILARR[0]="${USER%@*}"
-  MAILARR[1]="${USER#*@}"
+  USER="${EMAIL%@*}"
+  DOMAIN="${EMAIL#*@}"
 
-  # ${USER} must not contain /s and other syntactic characters
-  UNESCAPED_USER="${USER}"
-  USER=$(escape "${USER}")
+  # ${EMAIL} must not contain /s and other syntactic characters
+  UNESCAPED_EMAIL="${EMAIL}"
+  EMAIL=$(escape "${EMAIL}")
 
   if [[ -f ${DATABASE} ]]
   then
-    if ! sed -i "/^${USER}|/d" "${DATABASE}"
+    if ! sed -i "/^${EMAIL}|/d" "${DATABASE}"
     then
-      echo "${UNESCAPED_USER} couldn't be deleted in ${DATABASE}." >&2
+      echo "${UNESCAPED_EMAIL} couldn't be deleted in ${DATABASE}." >&2
       ERROR=true
     fi
   fi
 
   if [[ -f ${ALIAS_DATABASE} ]]
   then
-    # delete all aliases where the user is the only recipient( " ${USER$}" )
-    # delete user only for all aliases that deliver to multiple recipients ( ",${USER}" "${USER,}" )
+    # delete all aliases where the user is the only recipient( " ${EMAIL}" )
+    # delete user only for all aliases that deliver to multiple recipients ( ",${EMAIL}" "${EMAIL,}" )
     if sed -i \
-      -e "/ ${USER}$/d" -e "s/,${USER}//g" -e "s/${USER},//g" \
+      -e "/ ${EMAIL}$/d" -e "s/,${EMAIL}//g" -e "s/${EMAIL},//g" \
       "${ALIAS_DATABASE}"
     then
-      echo "${UNESCAPED_USER} and potential aliases deleted."
+      echo "${UNESCAPED_EMAIL} and potential aliases deleted."
     else
-      echo "Aliases for ${UNESCAPED_USER} couldn't be deleted in ${ALIAS_DATABASE}." >&2
+      echo "Aliases for ${UNESCAPED_EMAIL} couldn't be deleted in ${ALIAS_DATABASE}." >&2
       ERROR=true
     fi
   fi
@@ -131,21 +130,23 @@ fi
   # remove quota directives
   if [[ -f ${QUOTA_DATABASE} ]]
   then
-    if ! sed -i -e "/^${USER}:.*$/d" "${QUOTA_DATABASE}"
+    if ! sed -i -e "/^${EMAIL}:.*$/d" "${QUOTA_DATABASE}"
     then
-      echo "Quota for ${UNESCAPED_USER} couldn't be deleted in ${QUOTA_DATABASE}." >&2
+      echo "Quota for ${UNESCAPED_EMAIL} couldn't be deleted in ${QUOTA_DATABASE}." >&2
     fi
   fi
 
   if ! ${MAILDEL}
   then
-    echo "Leaving the mailbox untouched. If you want to delete it at a later point use 'sudo docker exec mail rm -R /var/mail/${MAILARR[1]}/${MAILARR[0]}'"
+    echo "Leaving the mailbox untouched.
+If you want to delete it at a later point,
+use 'sudo docker exec mailserver rm -R /var/mail/${DOMAIN}/${USER}'"
     exit 0
   fi
 
-  if [[ -e "/var/mail/${MAILARR[1]}/${MAILARR[0]}" ]]
+  if [[ -e "/var/mail/${DOMAIN}/${USER}" ]]
   then
-    if rm -R "/var/mail/${MAILARR[1]}/${MAILARR[0]}"
+    if rm -R "/var/mail/${DOMAIN}/${USER}"
     then
       echo "Mailbox deleted."
     else
@@ -153,11 +154,11 @@ fi
       ERROR=true
     fi
   else
-    echo "Mailbox directory '/var/mail/${MAILARR[1]}/${MAILARR[0]}' did not exist." >&2
+    echo "Mailbox directory '/var/mail/${DOMAIN}/${USER}' did not exist." >&2
     ERROR=true
   fi
 
-  ${ERROR} && errex 'Errors encountered.'
+  ${ERROR} && errex 'See the messages above.'
 
 ) 200< "${DATABASE}"
 
