sqlite for storage

diff --git a/target/bin/delmailuser b/target/bin/delmailuser
--- a/target/bin/delmailuser
+++ b/target/bin/delmailuser
@@ -1,9 +1,6 @@
 #!bin/bash
 # vim: et ai si ts=2 sts=2 sw=2
 
-DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}
-ALIAS_DATABASE="/tmp/docker-mailserver/postfix-virtual.cf"
-
 usage() {
   echo "Usage: delmailuser <-y> <user@domain> <user2@anotherdomain> ..."
   echo "  -y: don't prompt for confirmations"
@@ -32,27 +29,49 @@ done
 shift $((OPTIND-1))
 
 [ -z "$@" ] && { usage; errex "No user specifed"; }
-[ -s "$DATABASE" ] || exit 0
-
-for USER in "$@"; do
-  #very simple plausibility check
-  [[ "$USER" != *"@"*"."* ]] && errex "No valid address: $USER"
-  MAILARR=(${USER//@/ })
-  # XXX $USER must not contain /s and other syntactic characters
-  USER=$(escape "$USER")
-  sed -i "/^"$USER"|/d" $DATABASE
-  [ $? != 0 ] && errex "$USER couldn't be deleted in $DATABASE. $?"
-  # Delete all aliases where the user is the only recipient( " $USER$" )
-  # Delete user only for all aliases that deliver to multiple recipients ( ",$USER" "$USER," )
-  sed -i -e "/ "$USER"$/d" \
-         -e "s/,"$USER"//g" \
-         -e "s/"$USER",//g" $ALIAS_DATABASE
-  [ $? = 0 ] && echo "$USER and potential aliases deleted." || errex "Aliases for $USER couldn't be deleted in $ALIAS_DATABASE. $?"
-  if [ "$MAILDEL" != "y" ]; then
-    read -p "Do you want to delete the maildir as well(all mails will be removed)?(y/n) " MAILDEL
-    echo
-  fi
-  [ "$MAILDEL" != "y" ] && errex "Leaving the maildir untouched. If you want to delete it at a later point use \"sudo docker exec mail rm -R /var/mail/${MAILARR[1]}/${MAILARR[0]}\""
-  rm -r -f /var/mail/${MAILARR[1]}/${MAILARR[0]}
-  [ $? = 0 ] && echo "Maildir deleted." || errex "Maildir couldn't be deleted: $?"
-done
+if [ -s /var/db/sqlite-mail.db ]; then
+  DATABASE=/var/db/sqlite-mail.db
+  for USER in "$@"; do
+    #very simple plausibility check
+    [[ "$USER" != *"@"*"."* ]] && errex "No valid address: $USER"
+    MAILARR=(${USER//@/ })
+    # XXX $USER must not contain /s and other syntactic characters
+    USER=$(escape "$USER")
+    /usr/bin/sqlite3 $DATABASE "DELETE FROM mailbox WHERE username='${USER}';"
+    /usr/bin/sqlite3 $DATABASE "DELETE FROM alias WHERE address='${USER}' OR goto='${USER}';"
+    [ $? = 0 ] && echo "$USER and potential aliases deleted." || errex "Aliases for $USER couldn't be deleted in $ALIAS_DATABASE. $?"
+    if [ "$MAILDEL" != "y" ]; then
+      read -p "Do you want to delete the maildir as well(all mails will be removed)?(y/n) " MAILDEL
+      echo
+    fi
+    [ "$MAILDEL" != "y" ] && errex "Leaving the maildir untouched. If you want to delete it at a later point use \"sudo docker exec mail rm -R /var/mail/${MAILARR[1]}/${MAILARR[0]}\""
+    rm -r -f /var/mail/${MAILARR[1]}/${MAILARR[0]}
+    [ $? = 0 ] && echo "Maildir deleted." || errex "Maildir couldn't be deleted: $?"
+  done
+else
+  DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}
+  ALIAS_DATABASE="/tmp/docker-mailserver/postfix-virtual.cf"
+  [ -s "$DATABASE" ] || exit 0
+  for USER in "$@"; do
+    #very simple plausibility check
+    [[ "$USER" != *"@"*"."* ]] && errex "No valid address: $USER"
+    MAILARR=(${USER//@/ })
+    # XXX $USER must not contain /s and other syntactic characters
+    USER=$(escape "$USER")
+    sed -i "/^"$USER"|/d" $DATABASE
+    [ $? != 0 ] && errex "$USER couldn't be deleted in $DATABASE. $?"
+    # Delete all aliases where the user is the only recipient( " $USER$" )
+    # Delete user only for all aliases that deliver to multiple recipients ( ",$USER" "$USER," )
+    sed -i -e "/ "$USER"$/d" \
+           -e "s/,"$USER"//g" \
+           -e "s/"$USER",//g" $ALIAS_DATABASE
+    [ $? = 0 ] && echo "$USER and potential aliases deleted." || errex "Aliases for $USER couldn't be deleted in $ALIAS_DATABASE. $?"
+    if [ "$MAILDEL" != "y" ]; then
+      read -p "Do you want to delete the maildir as well(all mails will be removed)?(y/n) " MAILDEL
+      echo
+    fi
+    [ "$MAILDEL" != "y" ] && errex "Leaving the maildir untouched. If you want to delete it at a later point use \"sudo docker exec mail rm -R /var/mail/${MAILARR[1]}/${MAILARR[0]}\""
+    rm -r -f /var/mail/${MAILARR[1]}/${MAILARR[0]}
+    [ $? = 0 ] && echo "Maildir deleted." || errex "Maildir couldn't be deleted: $?"
+  done
+fi
