Rewrote perl script in bash for better maintainability

diff --git a/target/bin/fetchmailrc_split b/target/bin/fetchmailrc_split
--- a/target/bin/fetchmailrc_split
+++ b/target/bin/fetchmailrc_split
@@ -1,24 +1,56 @@
-#!/usr/bin/perl
+#!/bin/bash
+# Description: This script will split the content of /etc/fetchmailrc into
+#              smaller fetchmailrc files per server [poll] entries. Each
+#              separate fetchmailrc file is stored in /etc/fetchmailrc.d
+#
+#              The mail purpose for this is to work around what is known 
+#              as the Fetchmail IMAP idle issue.
+#
 
-my $defaults = "";
-my $server=0;
+# Global variables
+FETCHMAILRC="/etc/fetchmailrc"
+FETCHMAILRCD="/etc/fetchmailrc.d"
+DEFAULT_FILE="${FETCHMAILRCD}/defaults"
 
-open(CONF, "<", "/etc/fetchmailrc") || die "No fetchmail config file found: $!";
-my $fh;
-my $i = 0;
-while(<CONF>){
-	if($_ =~ m/poll/){
-		close($fh);
-		open($fh, ">", "/etc/fetchmailrc.d/fetchmail-$i.rc");
-		$i++;
-		$server = 1;
-		print $fh $defaults;
-		print $fh $_;
-	} elsif ($server == 0) {
-		$defaults .= $_;
-	} else {
-		print $fh $_;
-	}
-}
-close(CONF);
-close($fh);
+if [ ! -f "${FETCHMAILRC}" ]
+then
+	echo "Error: File ${FETCHMAILRC} not found"
+	exit 1
+fi
+
+if [ ! -d "${FETCHMAILRCD}" ]
+then
+	mkdir ${FETCHMAILRCD}
+	if [ "$?" -ne 0 ]
+	then
+		echo "Error: Unable to create folder ${FETCHMAILRCD}"
+		exit 1
+	fi
+fi
+
+COUNTER=0
+SERVER=0
+while read line
+do
+	if [[ "${line}" =~ poll ]]
+	then
+		# If we read "poll" then we reached a new server definition
+		# We need to create a new file with fetchmail defaults from
+		# /etc/fetcmailrc
+		COUNTER=$((COUNTER+1))
+		SERVER=1
+		cat "${DEFAULT_FILE}" > "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
+		echo "${line}" >> "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
+	elif [ "${SERVER}" -eq 0 ]
+	then
+		# We have not yet found "poll". Let's assume we are still reading
+		# the default settings from /etc/fetchmailrc file
+		echo "${line}" >> ${DEFAULT_FILE}
+	else
+		# Just the server settings that need to be added to the specific rc.d file
+		echo "${line}" >> "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
+	fi
+done < "${FETCHMAILRC}"
+
+# Cleaning
+rm "${DEFAULT_FILE}"
