apply PR review feedback

diff --git a/target/bin/sedfile b/target/bin/sedfile
--- a/target/bin/sedfile
+++ b/target/bin/sedfile
@@ -18,10 +18,11 @@ SKIP_ERROR=0
 
 if [[ ${#} -lt 3 ]]
 then
+  echo 'Error: At least three parameters must be given'
   __usage
-  echo 'At least three parameters must be given' >&2
+  echo
   exit 1
-fi
+fi >&2
 
 [[ -f /CONTAINER_START ]] && SKIP_ERROR=1 # hide error if container was restarted
 if [[ ${1} == '--strict' ]]               # show error every time
@@ -40,7 +41,7 @@ NEW=$(${HASHTOOL} "${FILE}")
 # fail if file was not modified
 if [[ ${OLD} == "${NEW}" ]] && [[ ${SKIP_ERROR} -eq 0 ]]
 then
-  echo "No difference after call to 'sed' in 'sedfile' (sed ${*})" >&2
+  echo "Error: No difference after call to 'sed' in 'sedfile' (sed ${*})" >&2
   exit 1
 fi
 
